#!	/bin/sh
#
# delivery script for %(driver_name)s driver
# automatically generated by encore $(date)s
#

DRIVER = %(driver_name)s
CPU=L865
KVER=2.6.24.7-rt27

# delivery paths
DRIVER_PATH=/acc/dsc/$ACC/$CPU/$KVER/$DRIVER/
LIB_PATH=/acc/local/$CPU/dg/$DRIVER/

# deliverable items
LIBS=lib_$DRIVER.$CPU.a lib_$DRIVER.h ${DRIVER}_regs.h vmeio.h
INSTPROGS=install_$DRIVER.sh transfer2insmod.awk
DRIVER_OBJECT=$DRIVER.ko
SOLIBS=$DRIVER.$CPU.so

dsc_install $INSTPROGS $DRIVER_OBJECT $SOLIBS $DRIVER_PATH
dsc_install $LIBS $LIB_PATH

