EXTRA_CFLAGS += -DCOMPILE_TIME=$(shell date +%s) -g -Wall \
	'-DDRIVER_NAME=$(DRIVER_NAME)' \
	-I/acc/src/dsc/drivers/vmebridge/driver \
	-I/acc/src/dsc/drivers/cohtdrep/lewis/vmeio-drivers/vmeio/include

obj-m:=vmeio.o
