#!   /usr/bin/env	python
#    coding: utf8

import sys
import os
import errno
import stat
import datetime
import csv
import cx_Oracle
from os.path import join
from optparse import OptionParser

db_am_translate = {
    2 : 0x39,
    4 : 0x2f,
    5 : 0x29,
    7 : 0x9,
}

register_field_list = [
    'name',
    'rwmode',
    'block',
    'block_address_space',
    'block_offset',
    'register_offset',
    'offset',
    'wordsize',
    'depth',
    'description',
    'data_width',
    ]

register_query = '''
select name,
    rwmode,
    block,
    mb.address as block_address_space,
    nvl(mb.offsetval,0) as block_offsetval,
    mr.offsetval as register_offset,
    mr.offsetval + nvl(mb.offsetval,0) as offset,
    wordsize,
    depthval as depth,
    mr.description as description,
    case mb.address
    	when 1 then ht.initdsize
	when 2 then ht.nextdsize
    end as data_width
from moduleregisters mr join moduleblocks mb
        using (block, moduletype_id)
    join hard_types ht
        on moduletype_id = ht.hwtype_id
where ht.hwtype = :hwtype
order by block, block_offsetval, register_offset
'''

module_field_list = [
    'name',
    'description',
    'level',
    'data_width1',
    'data_width2',
    'size1',
    'size2',
    'am1',
    'am2'
]

module_query = '''
select hwtype as name,
    description,
    ilevel,
    initdsize as data_width1,
    nextdsize as data_width2,
    initrangeval as size1,
    nextrangeval as size2,
    initasize as am1,
    nextasize as am2
from hard_types ht
where ht.hwtype = :hwtype
'''

cursor = cx_Oracle.connect(user='copub', password='co').cursor()


def get_module_data(module_name):
    """get module data

    Return a dictionary with module data, and a list of dicts
    with register properties
    """

    cursor.execute(module_query, hwtype=module_name)
    modtuple = cursor.fetchone()
    module_data = dict(zip(module_field_list, modtuple))

    cursor.execute(register_query, hwtype=module_name)
    register_data = [ dict(zip(register_field_list, row)) for row in cursor ]

    return module_data, register_data

def gen_plain_file(register_list, filename):
    """given a list of dicts with registers, construct a columnated file"""

    out = open(filename, 'wb')
    for reg in register_list:
        for key in register_field_list:
            out.write('%s\t' % reg[key])
        out.write('\n')
    out.close()

def gen_csv_file(register_list, filename):
    """given a list of dicts with registers, construct a CSV file"""

    out = csv.DictWriter(open(filename, 'wb'), register_field_list)
    for reg in register_list:
        out.writerow(reg)

def gen_register_struct(register_list, module_name):
    """create a C structure definition for this register list"""

    # generate include file
    template = file(regs_h_template).read()
    register_names = [ reg['name'] + ',\n' for reg in register_list ]
    register_names = ''.join(register_names)
    driver_name = module_name
    device_name = driver_name.upper()
    include_file = template % locals()

    cstruct = [ '#include "rf_vtu_regs.h"\n\n',
        'struct encore_reginfo %s_registers[] = {\n\n' % module_name ]
    for reg in register_list:
        cstruct.append('[%(name)s] = {\n' % reg)
        cstruct.append('''\
\t.name	        	= "%(name)s",
\t.rwmode      		= "%(rwmode)s",
\t.block       		= %(block)d,
\t.block_address_space	= %(block_address_space)d,
\t.block_offset		= 0x%(block_offset)x,
\t.register_offset	= 0x%(register_offset)x,
\t.offset			= 0x%(offset)x,
\t.wordsize	    	= "%(wordsize)s",
\t.depth       		= 0x%(depth)x,
\t.description		= "%(description)s",
\t.data_width		= %(data_width)d,'''
                       '\n    },\n\n''' % reg )
    cstruct.append('};\n\n')
    cstruct.append(
	'int %s_nregs = '
	'sizeof(%s_registers)/sizeof(%s_registers[0]);\n' % (
		module_name, module_name, module_name))
    c_file =  ''.join(cstruct)
    return include_file, c_file

def gen_register_struct_file(register_list, module_name, hname, cname):
    """generate a C file with struct encore definitions"""
    h, c = gen_register_struct(register_list, module_name)
    outh = file(hname, 'w')
    outh.write(h)
    outh.close()
    outc = file(cname, 'w')
    outc.write(c)
    outc.close()

def gen_offsets(register_list):
    """generate offset list #define's"""

    define_template = "#define\t%(offset_name)-16s\t0x%(offset)08x\n"

    defines = []
    for register in register_list:
        name = register['name']
        offset = int(register['offset'])
        offset_name = 'OFFSET_%s' % name
        define = define_template % locals()
        defines.append(define)
    return ''.join(defines)

def gen_lib_decls(register_list, prefix="vmeio"):
    """produce declarations for the get/set user lib functions"""
    decl_template = """
int %(driver_name)s_set_%(register_name)s (struct __vsl_device *handle, %(argtype)s value);
int %(driver_name)s_get_%(register_name)s (struct __vsl_device *handle, %(argtype)s *value);"""
    decls = []
    for register in register_list:
        driver_name = prefix
        register_name = register['name']
        argtype = register['wordsize']
        decl = decl_template % locals()
        decls.append(decl)
    return ''.join(decls)

def gen_lib_calls(register_list, prefix="vmeio"):
    """produce code for the get/set user lib functions"""
    call_template = """
int %(driver_name)s_set_%(register_name)s(struct __vsl_device *handle, %(argtype)s value) {
    return usr_raw_write(%(offset_name)s, value);
}

int %(driver_name)s_get_%(register_name)s(struct __vsl_device *handle, %(argtype)s *value) {
    return usr_raw_read(%(offset_name)s, *value);
}
"""
    calls = []
    for register in register_list:
        driver_name = prefix
        register_name = register['name']
        argtype = register['wordsize']
        offset_name = 'OFFSET_%s' % register_name
        call = call_template % locals()
        calls.append(call)
    return ''.join(calls)

def gen_h_file(register_list, libname, filename):
    """produce a lib<module>.h user library header"""
    h_file_header = """#include "vmeio_support.h"\n\n"""

    out = open(filename, 'wb')
    out.write(h_file_header)
    out.write(gen_offsets(register_list))
    out.write('\n')
    out.write(gen_lib_decls(register_list))
    out.close()

def gen_c_file(register_list, libname, filename):
    """produce a lib<module>.c user library module"""
    c_file_header = """#include "%s.h"\n\n""" % libname

    out = open(filename, 'wb')
    out.write(c_file_header)
    out.write(gen_lib_calls(register_list))
    out.close()

def gen_regs(register_list, module_name):

    rwmode_translate = {
        "rw"	: "RW",
        "rc"	: "RO",
        "rc"	: "RO",
        "r"	    : "RO",
        "w" 	: "RW",
        "rw"	: "RW",
        "e"     : "WO",
        "rc"	: "RO",
        "rwc"	: "RW",
    }

    size_translate = {
        'long'  : 4,
        'short' : 2,
        'char'  : 1,
    }

    row_template = ( "$\t%(register_name)-16s\t%(rwflags)2s\t"
            "0x%(offset)08X\t%(size)d\t%(window)d\t%(depth)s\n")
    regs = []
    for register in register_list:
        register_name = register['name']
        rwflags = rwmode_translate[register['rwmode']]
        offset = int(register['offset'])
        size = int(size_translate[register['wordsize']])
        window = 1
        depth = int(register['depth'])
        row = row_template % locals()
        regs.append(row)
    return ''.join(regs)

def gen_regs_file(register_list, module_name):
    """produce a .regs file"""

    name = module_name.upper()
    header = """NAME %s

  RegName		RwFlags	Offset		Size	Window	Depth

""" % name

    upper_name = name.upper()
    out = open(upper_name+'.regs', 'wb')
    out.write(header)
    out.write(gen_regs(register_list, upper_name))
    out.close()

def gen_makefile(driver_name, module_name, filename):
    """produce a Makefile for the library"""

    template = file(makefile_template).read()

    date = datetime.datetime.now().isoformat(' ')
    makefile = template % locals()
    out = open(filename, 'wb')
    out.write(makefile)
    out.close()

def gen_kbuild(driver_name, module_name, filename):
    """produce a Kbuild for the driver"""

    template = file(kbuild_template).read()

    date = datetime.datetime.now().isoformat(' ')
    kbuild = template % locals()
    out = open(filename, 'wb')
    out.write(kbuild)
    out.close()

def gen_install_script(device_name, driver_name,
	output_file, transfer='/etc/transfer.ref'):

    template = file(instprog_template).read()

    date = datetime.datetime.now().isoformat(' ')
    out = file(output_file, 'w')
    out.write(template % locals())
    out.close()

def make_out_dir(dirname, kill=False):
    try:
        isdir = stat.S_ISDIR(os.stat(dirname).st_mode)
        if not kill and raw_input(dirname +
                ' already exists, remove? (y/N) ') != 'y':
            return -errno.ENOENT

        for root, dirs, files in os.walk(dirname, topdown=False):
            for name in files:
                os.remove(os.path.join(root, name))
            for name in dirs:
                os.rmdir(os.path.join(root, name))
        os.rmdir(dirname)
        return os.mkdir(dirname)
    except OSError:
        return os.mkdir(dirname)

def main():

    # option processing
    usage = 'usage: dbexctract.py [options] MODULE_NAME'

    parser = OptionParser(usage=usage)
    parser.add_option("--plain", dest="plain", action="store",
                        help="create a plaintext file with register data",
                        metavar="FILE")
    parser.add_option("--regs", action="store_true", dest="regs",
                        help="create a .regs file for encore v1.0 compat",
                        metavar="FILE")
    parser.add_option("-q", "--quiet",
                      action="store_false", dest="verbose", default=True,
                      help="don't print status messages to stdout")
    parser.add_option("-k", "--kill",
                      action="store_true", dest="kill", default=False,
                      help="kill destination directory if it exists")
    (options, args) = parser.parse_args(sys.argv)

    # only positional parameter, module name
    if len(args) != 2:
        parser.print_help()
        sys.exit(1)
    module_name = args[1].upper()

    # prepare output paths
    driver_name   = module_name.lower()
    output_dir    = driver_name
    libname       = 'lib%s' % driver_name
    lib_h         = join(output_dir, libname + '.h')
    lib_c         = join(output_dir, libname + '.c')
    makefile      = join(output_dir, 'Makefile')
    kbuild        = join(output_dir, 'Kbuild')
    regs_csv      = join(output_dir, driver_name + '.csv')
    regs_h	      = join(output_dir, driver_name + '_regs.h')
    regs_c	      = join(output_dir, driver_name + '_regs.c')
    install_sh	  = join(output_dir, 'install_' + driver_name + '.sh')

    if make_out_dir(output_dir, options.kill):
        print 'could not make output dir ' + output_dir
        sys.exit(1)

    module_data, register_list  = get_module_data(module_name)
    if not register_list:
        print 'no data for module %s in CCDB, exiting' % module_name
        sys.exit(1)

    # copy verbatim files and locate templates
    # cwd = os.path.dirname(sys.argv[0])
    for f in verbatim_files:
        from_ = os.path.join(templates_dir, f)
        to    = os.path.join(output_dir, f)
        if f == 'vmeio.c':
            to = os.path.join(output_dir, driver_name + '.c')
	os.system('cp "%s" "%s"' % (from_, to))

    # driver fileset generation
    gen_csv_file(register_list, regs_csv)
    gen_register_struct_file(register_list, driver_name, regs_h, regs_c)
    gen_h_file(register_list, libname, lib_h)
    gen_c_file(register_list, libname, lib_c)
    gen_makefile(driver_name, module_name, makefile)
    gen_kbuild(driver_name, module_name, kbuild)
    gen_install_script(module_name, driver_name, install_sh)

    # optional data files generation
    registers = dict([ (regdata['name'], regdata)
                        for regdata in register_list ])
    if options.plain:
        plain_filename =join(output_dir, options.plain)
        gen_plain_file(register_list, plain_filename)
    if options.regs:
        regs_filename = join(output_dir, module_name)
        gen_regs_file(register_list, regs_filename)

# verbatim files and templates
cwd = '.'
templates_dir = os.path.join(cwd, 'templates')
makefile_template = os.path.join(templates_dir, 'Makefile')
kbuild_template = os.path.join(templates_dir, 'Kbuild')
instprog_template = os.path.join(templates_dir, 'install.sh')
regs_h_template = os.path.join(templates_dir, 'rf_vtu_regs.h')
verbatim_files = [
    'vmeio.c',
    'vmeio.h',
    'Module.symvers.vmebus',
    'libencore.c',
    'libencore.h',
    'vmeio_support.c',
    'vmeio_support.h',
    'transfer2insmod.awk',
]

if __name__ == '__main__':

    main()

