#!/bin/sh

root=/acc/src/dsc/drivers/cohtdrep/lewis/development-vmeio-drivers

encr=$root/encore
dsrc=$root/vmeio
ltar=`echo $1 | $encr/tolower`
utar=`echo $1 | $encr/toupper`
tnam=`echo $ltar"test"`

drvr=`pwd`/$ltar/driver
supt=`pwd`/$ltar/support
test=`pwd`/$ltar/support_test
regs=`pwd`/$ltar/awk/regs
ulib=`pwd`/$ltar/awk/lib
incl=`pwd`/$ltar/include

echo "insencore [<driver name>] [<cpu type> [<kernel version>] [<lab/oper/operlhc>]]]"
echo "insencore " $1 " " $2 " " $3 " " $4
echo
sleep 1

if [ $1 ]
then
   echo
   echo Installing driver, library and test program from directory ./$ltar

   if [ -f ./$ltar ]
   then

      cd ./$ltar

      if [ $2 ]
      then
	 cpu=$2
      else
	 cpu=L865
      fi

      if [ $3 ]
      then
	 kver=$3
      else
	 kver=2.6.24.7-rt27
      fi

      if [ $4 ]
      then
	 cmpx=$4
      else
	 cmpx=lab
      fi

      echo
      echo "insencore: Using CPU="$cpu " KVER="$kver " COMPLEX="$cmpx
      echo

      place=/acc/dsc/$cmpx/$cpu/$kver
      if [ -f $place/$ltar ]
	 echo "insencore: Using pre-existing druver target directory: " $place/$ltar
      else
	 echo "insencore: Creating driver target directory: " $place/$ltar
	 mkdir $place/$ltar
	 chmod g+w $place/$ltar
      fi
      echo "insencore: Installing: " $ltar.ko " in " $place/$ltar
      cd ./$ltar/driver; dsc_install $ltar.ko $place/$ltar

      place=/acc/dsc/$cmpx/$cpu
      if [ -f $place/$ltar ]
	 echo "insencore: Using pre-existing program target directory: " $place/$ltar
      else
	 echo "insencore: Creating program target directory: " $place/$ltar
	 mkdir $place/$ltar
	 chmod g+w $place/$ltar
      fi
      echo "insencore: Installing: test program in " $place/$ltar
      cd ./support_test; dsc_install vmeiotest.$cpu test$ltar vmeiotest.config $place/$ltar

      place=/ps/local/$cpu/drv
      if [ -f $place/$ltar ]
	 echo "insencore: Using pre-existing library target directory: " $place/$ltar
      else
	 echo "insencore: Creating library target directory: " $place/$ltar
	 mkdir $place/$ltar
	 chmod g+w $place/$ltar
      fi
      echo "insencore: Installing: libraries and include files in " $place/$ltar
      cd $supt; dsc_install vmeio_support.$cpu.a $place/$ltar
      cd $supt; dsc_install vmeio_support.h $place/$ltar
      cd $ulib; dsc_install lib$ltar.$cpu.a $place/$ltar
      cd $ulib; dsc_install lib$ltar.h $place/$ltar
      cd $drvr; dsc_install user_driver_parameters.h $place/$ltar
      cd $drvr; dsc_install vmeio.h $place/$ltar
      cd $incl; dsc_install vmebus.h $place/$ltar

   else

      echo "No such directory" `pwd`/$ltar
   fi

else

   cat $encr/README
fi
