#!/bin/sh

# BE/CO/HT Julian Lewis Thu 27th/Jan/2011 julian.lewis@cern.ch
# insencore driver, test and library installer.
#
#The three variables $srce, $dest and $libd should be set to
#point to the vmeio-drivers sources wherever we decide that should be,
#the root destination directory where we install stuff, it can be changed
#/tmp for testing; and finally the root directory for libraries and includes.
#When testing with /tmp you should create the same directory tree as is in
#the real $dest, ie /tmp/cpu/kver etc. This script will not attempt to
#create generic directories that should be already present.

srce=/acc/src/dsc/drivers/cohtdrep/lewis/vmeio-drivers
#srce=/acc/src/dsc/drivers/cohtdrep/lewis/development-vmeio-drivers
dest=/acc/dsc
#dest=/tmp
libd=/ps/local
#libd=/tmp

encr=$srce/encore
dsrc=$srce/vmeio
ltar=`echo $1 | tr '[A-Z]' '[a-z]'`
utar=`echo $1 | tr '[A-Z]' '[a-z]'`
tnam=`echo $ltar"test"`
lnam=`echo "lib"$ltar`

wdir=`pwd`/$ltar
drvr=`pwd`/$ltar/driver
supt=`pwd`/$ltar/support
test=`pwd`/$ltar/support_test
regs=`pwd`/$ltar/awk/regs
ulib=`pwd`/$ltar/awk/lib/$ltar
incl=`pwd`/$ltar/include
inst=`pwd`/$ltar/awk/install
sysg=`pwd`/$ltar/awk/sysgo

echo "insencore $*"
sleep 1

if [ $# -lt 1 ] ; then
	echo "usage: $0 [<driver name>] [<cpu type> [<kernel version>] [<lab/oper/operlhc>]]]"
   	cat $encr/README
	exit 1
fi

echo
echo "Installing driver, library and test program from: " $wdir

# default script parameters
cpu=L865
kver=2.6.24.7-rt27
cmpx=lab

# override by command-line settings
if [ x"$2" != x"" ]; then
	cpu=$2
fi

if [ x"$3" != x"" ]; then
	kver=$3
fi

if [ x"$4" != x"" ] ; then
	cmpx=$4
fi

if [ ! -d $wdir ] ; then
	echo "No such directory $wdir"
	exit 1
fi
cd $wdir

echo
echo "insencore: Using CPU="$cpu " KVER="$kver " COMPLEX="$cmpx
echo

place=$dest/$cmpx/$cpu/$kver
if [ -d $place/$ltar ]; then
	echo "insencore: Using pre-existing driver target directory: " $place/$ltar
else
	echo "insencore: Creating driver target directory: " $place/$ltar
	mkdir $place/$ltar
	chmod g+w $place/$ltar
fi

echo "insencore: Installing: driver, sysgo and installer in " $place/$ltar
cd $drvr; dsc_install $ltar.ko $place/$ltar
cd $inst; dsc_install doinstall.bat geninstall.awk $place/$ltar
cd $sysg; dsc_install dosysgo.bat callsysgo.awk sysgo $place/$ltar

place=$dest/$cmpx/$cpu
if [ -d $place/$ltar ]; then
	echo "insencore: Using pre-existing program target directory: " $place/$ltar
else
	echo "insencore: Creating program target directory: " $place/$ltar
	mkdir $place/$ltar
	chmod g+w $place/$ltar
fi

echo "insencore: Installing: test program files in " $place/$ltar
cd $test; dsc_install vmeiotest.$cpu $tnam vmeiotest.config $place/$ltar

place=$libd/$cpu/drv
if [ -d $place/$ltar ]; then
	echo "insencore: Using pre-existing library target directory: " $place/$ltar
else
	echo "insencore: Creating library target directory: " $place/$ltar
	mkdir $place/$ltar
	chmod g+w $place/$ltar
fi

echo "insencore: Installing: libraries and include files in " $place/$ltar
cd $supt; dsc_install vmeio_support.$cpu.a $place/$ltar
cd $supt; dsc_install vmeio_support.h $place/$ltar
cd $ulib; dsc_install $lnam.$cpu.a $place/$ltar
cd $ulib; dsc_install $lnam.h $place/$ltar
cd $drvr; dsc_install user_driver_parameters.h $place/$ltar
cd $drvr; dsc_install vmeio.h $place/$ltar
cd $incl; dsc_install vmebus.h $place/$ltar

