# generated automatically by encore, date %(date)s

EXTRA_CFLAGS += -DCOMPILE_TIME=$(shell date +%s) -g -Wall \
	'-DDRIVER_NAME=$(DRIVER_NAME)' \
	-DENCORE_DAL \
	-I/acc/src/dsc/drivers/vmebridge/driver

obj-m := %(driver_name)s.o
